### PR TITLE
Refactor onnx.py to dynamically handle input and output shapes

### PR DESCRIPTION
**Pull request by wittyicon29**
- Removed hardcoded input shape `(3, 224, 224)` and output shape `[_, 1000]` in `run_with_data_on_device`.
- Dynamically retrieve input and output shapes using `session.get_inputs()` and `session.get_outputs()`.
- Adjusted tensor shapes and batch sizes to align with model specifications.
- Improved flexibility to support ONNX models with varying input/output dimensions.

### CODE REVIEW

**Comment by kellino** [comment]
Thank you @wittyicon29. We are still setting up CI and testing, so I will look at the PR before merging just to make sure that it fits with the changes I know to be coming, but a quick glance suggests it is good.

**Comment by wittyicon29** [comment]
Thank you for the update! @kellino

**Review by kellino — COMMENTED** [review]
Ideally, I'd like to get rid of as many python lists as we can from the code, but (eyeballing) this should work and will do for the moment. Without any tests in place yet, I'll merge this into dev and test it through use.

**Comment by wittyicon29** [comment]
Thank you for the update! and appreciate the review

**Pull request merged**
